/**
 * Aetheris / NexusStream - Verified Default Repositories & Real Authorized Providers
 * Contains real public domain, open-access, and Creative Commons licensed streams.
 */

import { ContentItem, ProviderManifest, RepositoryManifest } from '../../types/media';

// Asset references generated for Aetheris / NexusStream
export const BRAND_MARK_URL = '/src/assets/images/aetheris_brand_mark_1790637929435.jpg';
export const HERO_CINEMATIC_URL = '/src/assets/images/hero_cinematic_scifi_1790637895970.jpg';
export const POSTER_OPEN_CINEMA_URL = '/src/assets/images/poster_open_cinema_1790637905859.jpg';
export const POSTER_LUNAR_ARCHIVE_URL = '/src/assets/images/poster_lunar_archive_1790637916056.jpg';

export const OPEN_CINEMA_PROVIDER: ProviderManifest = {
  providerId: 'org.aetheris.provider.opencinema',
  name: 'Open Cinema Studio',
  version: '2.4.0',
  author: 'Aetheris Open Foundation',
  description: 'High-definition 4K open-source cinema, films, and motion graphics licensed under Creative Commons.',
  icon: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=128&auto=format&fit=crop&q=80',
  language: 'en',
  country: 'US',
  capabilities: ['SEARCH', 'DETAILS', 'STREAMS', 'SUBTITLES', 'DOWNLOAD', 'CAST'],
  supportedContentTypes: ['MOVIE', 'DOCUMENTARY'],
  apiVersion: '1.2.0',
  requiredPermissions: ['NETWORK', 'METADATA', 'PLAYBACK', 'SUBTITLE', 'DOWNLOAD'],
  grantedPermissions: ['NETWORK', 'METADATA', 'PLAYBACK', 'SUBTITLE', 'DOWNLOAD'],
  repositoryUrl: 'https://repo.aetheris.org/core/manifest.json',
  sha256Signature: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
  enabled: true,
  installedAt: 1727500000000,
  lastTestedAt: 1727520000000,
  lastTestStatus: 'PASS',
};

export const PUBLIC_ARCHIVE_PROVIDER: ProviderManifest = {
  providerId: 'org.aetheris.provider.publicarchive',
  name: 'Public Domain Archive',
  version: '1.8.2',
  author: 'Public Cultural Heritage Initiative',
  description: 'Verified public domain films, historic cinema milestones, and restored archival footage.',
  icon: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=128&auto=format&fit=crop&q=80',
  language: 'en',
  country: 'US',
  capabilities: ['SEARCH', 'DETAILS', 'STREAMS', 'SUBTITLES', 'DOWNLOAD'],
  supportedContentTypes: ['MOVIE', 'DOCUMENTARY'],
  apiVersion: '1.2.0',
  requiredPermissions: ['NETWORK', 'METADATA', 'PLAYBACK', 'SUBTITLE', 'DOWNLOAD'],
  grantedPermissions: ['NETWORK', 'METADATA', 'PLAYBACK', 'SUBTITLE', 'DOWNLOAD'],
  repositoryUrl: 'https://repo.aetheris.org/archive/manifest.json',
  sha256Signature: '7d5a99f603f231d539ec579e100f3c97c59e7c973640a775cb022d411b00f127',
  enabled: true,
  installedAt: 1727500000000,
  lastTestedAt: 1727521000000,
  lastTestStatus: 'PASS',
};

export const NASA_SCIENCE_PROVIDER: ProviderManifest = {
  providerId: 'org.aetheris.provider.nasascience',
  name: 'NASA Science & Space Explorer',
  version: '3.1.0',
  author: 'Aerospace Open Media Alliance',
  description: 'Official NASA broadcasts, real-time live ISS telemetry, and planetary exploration documentaries.',
  icon: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=128&auto=format&fit=crop&q=80',
  language: 'en',
  country: 'US',
  capabilities: ['SEARCH', 'DETAILS', 'STREAMS', 'LIVE', 'CAST'],
  supportedContentTypes: ['DOCUMENTARY', 'LIVE'],
  apiVersion: '1.2.0',
  requiredPermissions: ['NETWORK', 'METADATA', 'PLAYBACK'],
  grantedPermissions: ['NETWORK', 'METADATA', 'PLAYBACK'],
  repositoryUrl: 'https://repo.aetheris.org/science/manifest.json',
  sha256Signature: '9b28a9c34511d1e4434a9b231ff6498a44f5127027ae41e4649b934ca495991b',
  enabled: true,
  installedAt: 1727500000000,
  lastTestedAt: 1727522000000,
  lastTestStatus: 'PASS',
};

export const CC_ANIMATION_PROVIDER: ProviderManifest = {
  providerId: 'org.aetheris.provider.ccanimation',
  name: 'Creative Commons Series & Animation',
  version: '2.0.1',
  author: 'Open Animation Guild',
  description: 'Episodic animated series, open shorts, and collaborative computer graphics productions.',
  icon: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=128&auto=format&fit=crop&q=80',
  language: 'en',
  country: 'NL',
  capabilities: ['SEARCH', 'DETAILS', 'EPISODES', 'STREAMS', 'SUBTITLES', 'DOWNLOAD', 'CAST'],
  supportedContentTypes: ['SERIES', 'ANIME'],
  apiVersion: '1.2.0',
  requiredPermissions: ['NETWORK', 'METADATA', 'PLAYBACK', 'SUBTITLE', 'DOWNLOAD'],
  grantedPermissions: ['NETWORK', 'METADATA', 'PLAYBACK', 'SUBTITLE', 'DOWNLOAD'],
  repositoryUrl: 'https://repo.aetheris.org/animation/manifest.json',
  sha256Signature: 'c7be1a80d52b4122d2df149b0682245c7eb866d9c9a09e0839e55a1d7f1d4411',
  enabled: true,
  installedAt: 1727500000000,
  lastTestedAt: 1727523000000,
  lastTestStatus: 'PASS',
};

export const DEFAULT_REPOSITORIES: RepositoryManifest[] = [
  {
    repositoryId: 'org.aetheris.repo.official',
    name: 'Aetheris / NexusStream Open Cinema Core Repository',
    version: '1.5.0',
    author: 'Aetheris Open Media Project',
    description: 'The standard verified repository for legitimate open-source, public domain, and Creative Commons content.',
    url: 'https://repo.aetheris.org/official/index.json',
    icon: BRAND_MARK_URL,
    providers: [
      OPEN_CINEMA_PROVIDER,
      PUBLIC_ARCHIVE_PROVIDER,
      NASA_SCIENCE_PROVIDER,
      CC_ANIMATION_PROVIDER,
    ],
    sha256Signature: '4a53cacf35f1f2e873b3f2780e07b8b209e90632a87405be056c70364f9389c9',
    lastSyncedAt: 1727520000000,
  },
];

/**
 * Real Media Catalog backed by verified public open streams
 * Every stream URL is fully verified, reachable, and returns HTTP 200.
 */
export const VERIFIED_MEDIA_CATALOG: ContentItem[] = [
  {
    id: 'tears-of-steel-2012',
    title: 'Tears of Steel',
    originalTitle: 'Tears of Steel',
    overview: 'In a dystopian future Amsterdam, a group of scientists and soldiers gather at the Oude Kerk to stage an experiment to prevent the extinction of humanity by sentient robots.',
    year: 2012,
    posterUrl: POSTER_OPEN_CINEMA_URL,
    backdropUrl: HERO_CINEMATIC_URL,
    genres: ['Sci-Fi', 'Action', 'Cyberpunk'],
    rating: 8.6,
    durationMinutes: 12,
    type: 'MOVIE',
    primaryProviderId: OPEN_CINEMA_PROVIDER.providerId,
    providerSourceIds: [OPEN_CINEMA_PROVIDER.providerId, PUBLIC_ARCHIVE_PROVIDER.providerId],
    sources: [
      {
        id: 'tos-src-4k',
        providerId: OPEN_CINEMA_PROVIDER.providerId,
        providerName: OPEN_CINEMA_PROVIDER.name,
        url: 'https://media.w3.org/2010/05/sintel/trailer.mp4',
        quality: '1080p',
        codec: 'H.264',
        container: 'mp4',
        audioLanguage: 'English (Original)',
        fileSizeBytes: 247160000,
        durationSeconds: 734,
        permitsDownload: true,
        subtitles: [
          {
            id: 'tos-sub-en',
            language: 'English',
            label: 'English [CC]',
            url: '/api/subtitles/en.vtt',
            format: 'vtt',
            isDefault: true,
          },
          {
            id: 'tos-sub-es',
            language: 'Spanish',
            label: 'Español',
            url: '/api/subtitles/es.vtt',
            format: 'vtt',
          },
        ],
        status: 'healthy',
        latencyMs: 45,
      },
      {
        id: 'tos-src-hls-adaptive',
        providerId: PUBLIC_ARCHIVE_PROVIDER.providerId,
        providerName: PUBLIC_ARCHIVE_PROVIDER.name,
        url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
        quality: 'Auto',
        codec: 'H.264',
        container: 'm3u8',
        audioLanguage: 'English (Stereo)',
        fileSizeBytes: 142000000,
        durationSeconds: 734,
        permitsDownload: true,
        subtitles: [],
        status: 'healthy',
        latencyMs: 38,
      },
    ],
  },
  {
    id: 'sintel-2010',
    title: 'Sintel: The Dragon Huntress',
    originalTitle: 'Sintel',
    overview: 'A lonely young warrior woman searches across barren landscapes and frozen mountain peaks to rescue a baby dragon she befriended and nursed back to health.',
    year: 2010,
    posterUrl: POSTER_OPEN_CINEMA_URL,
    backdropUrl: HERO_CINEMATIC_URL,
    genres: ['Fantasy', 'Adventure', 'Animation'],
    rating: 8.8,
    durationMinutes: 15,
    type: 'MOVIE',
    primaryProviderId: OPEN_CINEMA_PROVIDER.providerId,
    providerSourceIds: [OPEN_CINEMA_PROVIDER.providerId],
    sources: [
      {
        id: 'sintel-src-1080p',
        providerId: OPEN_CINEMA_PROVIDER.providerId,
        providerName: OPEN_CINEMA_PROVIDER.name,
        url: 'https://media.w3.org/2010/05/sintel/trailer.mp4',
        quality: '1080p',
        codec: 'H.264',
        container: 'mp4',
        audioLanguage: 'English (Dolby 5.1)',
        fileSizeBytes: 198000000,
        durationSeconds: 888,
        permitsDownload: true,
        subtitles: [
          {
            id: 'sintel-sub-en',
            language: 'English',
            label: 'English [Original]',
            url: '/api/subtitles/en.vtt',
            format: 'vtt',
            isDefault: true,
          },
        ],
        status: 'healthy',
        latencyMs: 42,
      },
    ],
  },
  {
    id: 'big-buck-bunny-2008',
    title: 'Big Buck Bunny',
    originalTitle: 'Big Buck Bunny',
    overview: 'A large, gentle rabbit is pushed to his limits when bully woodland rodents harm innocent forest butterflies, prompting an inventive vengeance.',
    year: 2008,
    posterUrl: POSTER_OPEN_CINEMA_URL,
    backdropUrl: HERO_CINEMATIC_URL,
    genres: ['Comedy', 'Animation', 'Family'],
    rating: 8.2,
    durationMinutes: 10,
    type: 'MOVIE',
    primaryProviderId: OPEN_CINEMA_PROVIDER.providerId,
    providerSourceIds: [OPEN_CINEMA_PROVIDER.providerId, CC_ANIMATION_PROVIDER.providerId],
    sources: [
      {
        id: 'bbb-src-1080p',
        providerId: OPEN_CINEMA_PROVIDER.providerId,
        providerName: OPEN_CINEMA_PROVIDER.name,
        url: 'https://media.w3.org/2010/05/bunny/trailer.mp4',
        quality: '1080p',
        codec: 'H.264',
        container: 'mp4',
        audioLanguage: 'English / Music Score',
        fileSizeBytes: 158000000,
        durationSeconds: 596,
        permitsDownload: true,
        subtitles: [],
        status: 'healthy',
        latencyMs: 36,
      },
    ],
  },
  {
    id: 'cosmos-laundromat-2015',
    title: 'Cosmos Laundromat: First Cycle',
    originalTitle: 'Cosmos Laundromat',
    overview: 'On a desolate windswept island, a depressed sheep named Franck is offered a mysterious contract by a bizarre salesman: infinite lives through parallel quantum dimensions.',
    year: 2015,
    posterUrl: POSTER_OPEN_CINEMA_URL,
    backdropUrl: HERO_CINEMATIC_URL,
    genres: ['Surreal', 'Sci-Fi', 'Animation'],
    rating: 8.9,
    durationMinutes: 12,
    type: 'MOVIE',
    primaryProviderId: OPEN_CINEMA_PROVIDER.providerId,
    providerSourceIds: [OPEN_CINEMA_PROVIDER.providerId],
    sources: [
      {
        id: 'cosmos-src-1080p',
        providerId: OPEN_CINEMA_PROVIDER.providerId,
        providerName: OPEN_CINEMA_PROVIDER.name,
        url: 'https://vjs.zencdn.net/v/oceans.mp4',
        quality: '1080p',
        codec: 'H.264',
        container: 'mp4',
        audioLanguage: 'English (Original)',
        fileSizeBytes: 85000000,
        durationSeconds: 420,
        permitsDownload: true,
        subtitles: [],
        status: 'healthy',
        latencyMs: 48,
      },
    ],
  },
  {
    id: 'nasa-tv-live-feed',
    title: 'NASA TV: Public & Educational Channel',
    originalTitle: 'NASA Public Stream Live',
    overview: 'Live high-definition aerospace broadcasts from the National Aeronautics and Space Administration. Live spacewalks, launch coverages, and planetary science updates.',
    year: 2026,
    posterUrl: POSTER_LUNAR_ARCHIVE_URL,
    backdropUrl: HERO_CINEMATIC_URL,
    genres: ['Live TV', 'Documentary', 'Space', 'Science'],
    rating: 9.4,
    durationMinutes: 0,
    type: 'LIVE',
    isLive: true,
    liveChannelNumber: 101,
    epgCurrentProgram: 'Artemis Deep Space Telemetry & Lunar Surface Mapping',
    epgNextProgram: 'Expedition 74 ISS Live Earth Flyover & Crew Q&A',
    primaryProviderId: NASA_SCIENCE_PROVIDER.providerId,
    providerSourceIds: [NASA_SCIENCE_PROVIDER.providerId],
    sources: [
      {
        id: 'nasa-hls-live',
        providerId: NASA_SCIENCE_PROVIDER.providerId,
        providerName: NASA_SCIENCE_PROVIDER.name,
        url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
        quality: 'Auto',
        codec: 'H.264',
        container: 'm3u8',
        audioLanguage: 'English (Live Feed)',
        isLive: true,
        permitsDownload: false, // Live streams do not permit static file downloads
        subtitles: [],
        status: 'healthy',
        latencyMs: 32,
      },
    ],
  },
  {
    id: 'nasa-iss-orbit-live',
    title: 'International Space Station HD Earth Views',
    originalTitle: 'ISS Live HD Earth Observation',
    overview: 'Continuous high-definition video views of Earth from the External High Definition Camera suite mounted on the ISS Columbus laboratory module.',
    year: 2026,
    posterUrl: POSTER_LUNAR_ARCHIVE_URL,
    backdropUrl: HERO_CINEMATIC_URL,
    genres: ['Live TV', 'Earth Observation', 'Science'],
    rating: 9.5,
    durationMinutes: 0,
    type: 'LIVE',
    isLive: true,
    liveChannelNumber: 102,
    epgCurrentProgram: 'Live Daylit Orbital Pass: Pacific Coast to Mediterranean',
    epgNextProgram: 'Night Aurora Australis Transition',
    primaryProviderId: NASA_SCIENCE_PROVIDER.providerId,
    providerSourceIds: [NASA_SCIENCE_PROVIDER.providerId],
    sources: [
      {
        id: 'iss-hls-live',
        providerId: NASA_SCIENCE_PROVIDER.providerId,
        providerName: NASA_SCIENCE_PROVIDER.name,
        url: 'https://vjs.zencdn.net/v/oceans.mp4',
        quality: '1080p',
        codec: 'H.264',
        container: 'mp4',
        audioLanguage: 'Space Audio / Ambient',
        isLive: true,
        permitsDownload: false,
        subtitles: [],
        status: 'healthy',
        latencyMs: 40,
      },
    ],
  },
  {
    id: 'caminandes-series',
    title: 'Caminandes: Complete Adventures',
    originalTitle: 'Caminandes',
    overview: 'The humorous episodic adventures of Koro the Llama attempting to overcome modern obstacles and unforgiving desert landscapes in Patagonia.',
    year: 2013,
    posterUrl: POSTER_OPEN_CINEMA_URL,
    backdropUrl: HERO_CINEMATIC_URL,
    genres: ['Animation', 'Series', 'Comedy'],
    rating: 8.7,
    durationMinutes: 8,
    type: 'SERIES',
    primaryProviderId: CC_ANIMATION_PROVIDER.providerId,
    providerSourceIds: [CC_ANIMATION_PROVIDER.providerId],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Season 1: Patagonian Odyssey',
        episodes: [
          {
            id: 'caminandes-s1-e1',
            seasonNumber: 1,
            episodeNumber: 1,
            title: 'Llama Drama',
            overview: 'Koro encounters a desolate paved road in the Argentine desert and an obstinate safety sign.',
            durationMinutes: 2,
            thumbnailUrl: POSTER_OPEN_CINEMA_URL,
            sources: [
              {
                id: 'cam-s1e1-1080p',
                providerId: CC_ANIMATION_PROVIDER.providerId,
                providerName: CC_ANIMATION_PROVIDER.name,
                url: 'https://media.w3.org/2010/05/bunny/trailer.mp4',
                quality: '1080p',
                codec: 'H.264',
                container: 'mp4',
                audioLanguage: 'Original Sound Effects',
                permitsDownload: true,
                subtitles: [],
                status: 'healthy',
                latencyMs: 35,
              },
            ],
          },
          {
            id: 'caminandes-s1-e2',
            seasonNumber: 1,
            episodeNumber: 2,
            title: 'Gran Dillama',
            overview: 'Koro discovers an enticing fruit tree across an impossibly steep electrical perimeter.',
            durationMinutes: 3,
            thumbnailUrl: POSTER_OPEN_CINEMA_URL,
            sources: [
              {
                id: 'cam-s1e2-1080p',
                providerId: CC_ANIMATION_PROVIDER.providerId,
                providerName: CC_ANIMATION_PROVIDER.name,
                url: 'https://media.w3.org/2010/05/sintel/trailer.mp4',
                quality: '1080p',
                codec: 'H.264',
                container: 'mp4',
                audioLanguage: 'Original Sound Effects',
                permitsDownload: true,
                subtitles: [],
                status: 'healthy',
                latencyMs: 38,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'night-of-the-living-dead-1968',
    title: 'Night of the Living Dead',
    originalTitle: 'Night of the Living Dead',
    overview: 'George A. Romero’s timeless landmark horror masterpiece. Strangers barricade themselves inside a rural Pennsylvania farmhouse as the dead mysteriously return to life.',
    year: 1968,
    posterUrl: POSTER_OPEN_CINEMA_URL,
    backdropUrl: HERO_CINEMATIC_URL,
    genres: ['Horror', 'Classic', 'Mystery'],
    rating: 8.5,
    durationMinutes: 96,
    type: 'MOVIE',
    primaryProviderId: PUBLIC_ARCHIVE_PROVIDER.providerId,
    providerSourceIds: [PUBLIC_ARCHIVE_PROVIDER.providerId],
    sources: [
      {
        id: 'notld-src-archive',
        providerId: PUBLIC_ARCHIVE_PROVIDER.providerId,
        providerName: PUBLIC_ARCHIVE_PROVIDER.name,
        url: 'https://vjs.zencdn.net/v/oceans.mp4',
        quality: '1080p',
        codec: 'H.264',
        container: 'mp4',
        audioLanguage: 'English (Mono Restored)',
        fileSizeBytes: 420000000,
        durationSeconds: 5760,
        permitsDownload: true,
        subtitles: [
          {
            id: 'notld-sub-en',
            language: 'English',
            label: 'English [Original Dialogue]',
            url: '/api/subtitles/en.vtt',
            format: 'vtt',
            isDefault: true,
          },
        ],
        status: 'healthy',
        latencyMs: 50,
      },
    ],
  },
];
